openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: solid-spoon
  url: http://83.212.100.226:3001/v1
security:
- {}
tags:
- description: not yet ready
  name: person
paths:
  /person:
    post:
      operationId: createperson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/person'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'
          description: successful operation
      summary: Creates the data
      tags:
      - person
      x-eov-operation-handler: controllers/PersonController
  /person/{personId}:
    delete:
      operationId: deleteperson
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: personId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - person
      x-eov-operation-handler: controllers/PersonController
    get:
      operationId: getperson
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: personId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'
          description: successful operation
      summary: Get the element
      tags:
      - person
      x-eov-operation-handler: controllers/PersonController
    put:
      operationId: updateperson
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: personId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/person'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/person'
          description: successful operation
      summary: Updates the element
      tags:
      - person
      x-eov-operation-handler: controllers/PersonController
  /person/getAll:
    get:
      operationId: getAllperson
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/person'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - person
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/PersonController
  /person/getByParams:
    get:
      operationId: getByParamsperson
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/person'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - person
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/PersonController
components:
  schemas:
    person:
      example:
        fname: fname
        lname: lname
        cname: cname
        _id: _id
      properties:
        _id:
          type: string
        fname:
          type: string
        lname:
          type: string
        cname:
          type: string
      required:
      - cname
      - fname
      - lname
      type: object
